### PR TITLE
Update minimatch to avoid vulnerability

### PR DESCRIPTION
**Pull request by knownasilya**

### CODE REVIEW

**Comment by rwjblue** [comment]
Are there any breaking changes from 2.0.1 to 3.0.0?  Seems like there may be...

**Comment by knownasilya** [comment]
I'm assuming the tests would have caught any issues..

**Comment by rwjblue** [comment]
HEHE, so much faith!

**Comment by rwjblue** [comment]
Looks like they stopped bundling the browser build, I don't spot other breaking changes in the diff.

https://github.com/isaacs/minimatch/compare/v2.0.10...v3.0.2

**Comment by rwjblue** [comment]
LGTM

@stefanpenner - r?

**Comment by stefanpenner** [comment]
r+

**Comment by stefanpenner** [comment]
released as v1.0.2

**Comment by knownasilya** [comment]
Sweet.

**Comment by stefanpenner** [comment]
thanks @knownasilya !

**Pull request merged**
